VERSION="2.4.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
	"GC5TLOYRAEXMHSJ5H3CZYZVT22IZSDANO2COJLSCSVMZZRS7QUPXM6QT",
  	"GAUCEMTLRZ6G3YJWUMRNFCWJEFXVPDIYQG6S3R6VCLSRBIIQBVLPZ53D",
]

[DOCUMENTATION]
ORG_NAME="MayoCoin"
ORG_URL="https://mayocoin.cu.ma/"
ORG_LOGO="https://mayocoin.cu.ma/mayocoin.png"
ORG_DESCRIPTION="The Most Delicious Meme Coin on Stellar"
ORG_OFFICIAL_EMAIL="realmayocoin@gmail.com"

[[PRINCIPALS]]
name="Remarkable Mayonaise"
email="realmayocoin@gmail.com"

[[CURRENCIES]]
code="MayoCoin"
issuer="GC5TLOYRAEXMHSJ5H3CZYZVT22IZSDANO2COJLSCSVMZZRS7QUPXM6QT"
name="MayoCoin"
desc="The Most Delicious Meme Coin on Stellar"
image="https://mayocoin.cu.ma/mayocoin.png"
display_decimals=6
conditions="There will be only 18 778 580 398 MayoCoin in existence."
fixed_number=18778580398

[[CURRENCIES]]
code="Mayoneer"
issuer="GC5TLOYRAEXMHSJ5H3CZYZVT22IZSDANO2COJLSCSVMZZRS7QUPXM6QT"
name="Mayoneer NFT"
desc="Given to the first ten Mayoneers for services to MayoCoin."
image="https://mayocoin.cu.ma/mayoneer.png"
display_decimals=7
conditions="There will be only ten MayoCoin Mayoneer NFTs in existence."
fixed_number=1

[[CURRENCIES]]
code="TATER"
issuer="GCPDJSVXMDYFOMNVDLWHRQMPTIDBBWDSWHZLK2S3CQ6QXBQOR4544KCH"
name="Tater Tot"
desc="Crispy and delicious, what's not to like?"
image="https://mayocoin.cu.ma/tater_128x128.png"
display_decimals=7
conditions="There will be only 60 million Tater Tots in existence."
fixed_number=60000000

[[CURRENCIES]]
code="Slut"
name="Sluts"
issuer="GDK2ZPX5QSW523TG4NHG6ONIKNIXAINYNSGHOSEJAHEKDEC3WOCMP4V2"
is_asset_anchored=false
display_decimals=6
desc="Sluts are everywhere. How many do you own?"
image="https://mayocoin.cu.ma/sluts.png"
<<<<<<< HEAD
conditions="There will only ever be 69,626,467 Million Sluts"
=======
conditions="There will only ever be 69,626,467 Million Sluts"
>>>>>>> 2ccae05439a6aba8858e25311b5aa2862bf5e0d6
